### ISSUE TITLE
Bug Report: Main Music & Camera Zoom Stage

### ISSUE THREAD

**Issue by Whennosabenxd** [Vortex2Oblivion/LeatherEngine#13]
Well the 2 bugs:

- Freeplay:

Enter a freeplay song either exit or complete the song when you return to the freeplay menu no music (scroll effect doesn't have that problem)

- Stage Zoom Camera:

When you save the json the zoom configuration is not saved to modify it you have to enter the json to be able to customize it but in short when you save it the zoom is not saved

**Comment by Vortex2Oblivion** [comment]
The 2nd one is intentional
