### ISSUE TITLE
Enhancement: they are a lot

### ISSUE THREAD

**Issue by Whennosabenxd** [Vortex2Oblivion/LeatherEngine#14]
Silly ideas or good ones:
Also i use the google translator because too lazy to translate (The are part that are in Spanish i think) 

Good Ones:
-> Video Implementation
- Put videos instead of images
An example instead of the background being animated by images this is a video (In loop if so)
This to preserve the quality and performance (I think to improve it)
- Another in being able to put videos on a chart (That video would not stop the song would be part)
There are 2 variants of this, a script where the video occupies the entire screen
and the other one is in the (CamGame) that is, under the hud

Here is the link for help:
-https://gamebanana.com/tools/12156 (The sprit of the video)
-https://gamebanana.com/mods/426880 (Same but the one below the hud)

-> The double color in Health Bar
Someone had already requested it so I'll re-message it
-https://github.com/Leather128/LeatherEngine/issues/187-

My idea is to create an option that if set to "true" is activated
And put bar color, bar color2

A mod that put it on was MattWiik4WiiRemastered (I think it's called heaven)

-> Cool Effect Health bar

Universal Castatrophie (Zoro engine)
God Shaggy has a like an effect or idk

Here's the code:
  PlayState.instance.healthBar.createGradientBar([0xFF144800, 0xFF144800, 0xFF144800], [0xFF000000, 0xFF000000, 0xFFffee00]);

-> Ui Skin Oponnet:
That the opponent can have a different skin if another skin is selected if he does not use the same one that bf has
Let's say you didn't put anything for the same skin but if you chose a skin for the oponet then it applies
(Taken from pysch engien)

-> No Time bar
Its name says it, you can choose an option to not have the time bar

-> Extra Strums
Make a character have their own strum without having to share it with the other character

Let's say shaggy has his strumline and matt has his own strumline

(From Hypons, Astral Chaos, Haven)

-> Animated Icons (Winning & Loss)
Not only the neutral can also be Wining & Lossing

- Here the code (Psych) (I did not find the creator)
--animated icon script by me
--give credit if used -Classic1926
enableBFAnim = false
enableDadAnim = false
function onCreatePost()
     enableBFAnim = false
     enableDadAnim = false
     daBF = getProperty('boyfriend.curCharacter')
     daDAD = getProperty('dad.curCharacter')
     --if daBF == 'bf' or daBF == 'bf' or daBF == 'bf' or daBF == 'bf' then --UNCOMMIT TO ADD WHITELIST
     makeAnimatedLuaSprite('animated-bf', 'icons/'..daBF..'-animated', getProperty('iconP1.x'), getProperty('iconP1.y'))

     addAnimationByPrefix('animated-bf', 'idle', 'idle', 24, true)
     addAnimationByPrefix('animated-bf', 'lose', 'lose', 24, true)
     addAnimationByPrefix('animated-bf', 'win', 'win', 24, true)
     setObjectCamera('animated-bf', 'hud')
     addLuaSprite('animated-bf', true)
     setProperty('iconP1.visible',false)
     setObjectOrder('animated-bf', getObjectOrder('iconP1'))
     enableBFAnim = true
     --end

     --if daDAD == 'dad' or daDAD == 'dad' or daDAD == 'dad' or daDAD == 'dad' then --UNCOMMIT TO ADD WHITELIST
     makeAnimatedLuaSprite('animated-dad', 'icons/'..daDAD..'-animated', getProperty('iconP2.x'), getProperty('iconP2.y'))

     addAnimationByPrefix('animated-dad', 'idle', 'idle', 24, true)
     addAnimationByPrefix('animated-dad', 'lose', 'lose', 24, true)
     addAnimationByPrefix('animated-dad', 'win', 'win', 24, true)

     addLuaSprite('animated-dad', true)
     setProperty('iconP2.visible',false)
     setObjectCamera('animated-dad', 'hud')
     setObjectOrder('animated-dad', getObjectOrder('iconP2'))
     enableDadAnim = true
     --end
end
function onUpdate()
         if enableBFAnim then
setProperty('animated-bf.x', getProperty('iconP1.x'))
setProperty('animated-bf.y', getProperty('iconP1.y'))
         setProperty('animated-bf.alpha', getProperty('iconP1.alpha'))
setProperty('animated-bf.angle', getProperty('iconP1.angle'))
         setProperty('animated-bf.flipX', true)
         scaleObject('animated-bf', 1, 1)
         end
         if enableDadAnim then
         setProperty('animated-dad.x', getProperty('iconP2.x'))
setProperty('animated-dad.y', getProperty('iconP2.y'))
         setProperty('animated-dad.alpha', getProperty('iconP2.alpha'))
setProperty('animated-dad.angle', getProperty('iconP2.angle'))
         scaleObject('animated-dad', 1, 1)
         end
end
function onBeatHit()
if getProperty('health') > 1.6 then
         if enableBFAnim then
objectPlayAnimation('animated-bf','win',true);
         end
         if enableDadAnim then
         objectPlayAnimation('animated-dad','lose',true);
         end
elseif getProperty('health') < 0.4 then
         if enableBFAnim then
objectPlayAnimation('animated-bf','lose',true);
         end
         if enableDadAnim then
         objectPlayAnimation('animated-dad','win',true);
         end
else
         if enableBFAnim then
objectPlayAnimation('animated-bf','idle',true);
         end
         if enableDadAnim then
         objectPlayAnimation('animated-dad','idle',true);
         end
end
end

Not to good: (Well, they didn't really convince me)
-> Video Implementation
Here would be instead of images of the characters be videos (Characters,Menu Characters)

-> Set/Add Subtitles
Una implementacion de subtitulos
(Inspiracion del mod:friday-night-crunchin-v2)

-> Add Animation a change keys
Look to the pysch engine extra keys ther you will see

-> Move a note ONLY one note
la idea lo tome del mod sau
(Thezoroforce)

-> Toggle Cam Lock

**Comment by Vortex2Oblivion** [comment]
You can already do all those things
