### ISSUE TITLE
Enhancement: State scripts in all states

### ISSUE THREAD

**Issue by cherrythecool** [Vortex2Oblivion/LeatherEngine#23]
## What is your suggestion, and why should it be implemented?

Currently only MainMenuState has support for custom scripting. I believe all states should have this capability, maybe besides PlayState as that would be redundant, but who knows.

I believe it would be relatively easy to implement this system, most likely using a simple modification to MusicBeatState (and also MusicBeatSubstate) that would load scripts in the create function, most likely using Haxe's Type class to get the name and package of the class automatically (although doing it hardcoded could work just as well, to prevent things such as PlayState from having state scripting perhaps).

**Comment by Vortex2Oblivion** [comment]
You see I was going to do that but I was lazy and I haven't done the rest of them yet

**Comment by cherrythecool** [comment]
You still should though.

**Comment by Vortex2Oblivion** [comment]
Yes I will
