### ISSUE TITLE
Bug Report: Freeplay And FlxAnimate

### ISSUE THREAD

**Issue by Whennosabenxd** [Vortex2Oblivion/LeatherEngine#32]
Well I found 2 bugs
The first in freeplay with the new code that the "curMod" has means that the songs or the mere net do not appear, I don't know how it works
![Captura de pantalla 2023-11-16 104125](https://github.com/Vortex2Oblivion/LeatherEngine-Extended-Support/assets/124950042/ee0f0d7f-108c-42b8-8918-d00a4a1f088c)

What I did was delete the code you put

![Captura de pantalla 2023-11-16 105115](https://github.com/Vortex2Oblivion/LeatherEngine-Extended-Support/assets/124950042/80604023-9e94-4df1-aaeb-f5406dd8b66d)

Flx Animated:
The FlxAnimate when tested causes the file to not start

haxelib/flxanimate/git/flxanimate/frames/FlxAnimateFrames.hx:143: characters 30-36 : Field concat is declared 'override' but doesn't override any field

I think it's something from flxanimate itself since I updated the files but if it doesn't happen to you, maybe it's my problem.

If it doesn't work for you, put:
 (In the Project.xml)
//interp.variables.set('FlxAnimate', flxanimate.FlxAnimate); (In HScript)

**Comment by Vortex2Oblivion** [comment]
1:
Hit tab to switch mods, it's not written down anywhere yet.

2:
run 
```haxelib upgrade```
