### ISSUE TITLE
Bug Report: invisible button in developer options

### ISSUE THREAD

**Issue by fryman444** [Vortex2Oblivion/LeatherEngine#33]
the button that appears when turning on developer mode is able to be hovered over without dev mode on
![image_2023-11-18_105726508](https://github.com/Vortex2Oblivion/LeatherEngine-Extended-Support/assets/139307130/31f83647-41a1-494d-be0c-d156f55c42a5)

**Comment by Vortex2Oblivion** [comment]
yes im aware of this it was just a placeholder
