### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by Whennosabenxd** [Vortex2Oblivion/LeatherEngine#36]
How do I ensure that a UI skin is not affected by the notes colors:
Example: Voiid Chronicles (Notes are affected by colors)
![imagen](https://github.com/Vortex2Oblivion/LeatherEngine-Extended-Support/assets/124950042/690dc6d6-6391-4f78-8834-39578bb87797)

**Comment by Vortex2Oblivion** [comment]
in data/ui skins/your ui skin/ click on "default.txt" or whatever other note you want to change and on the last line, change ```true``` to ```false```

**Comment by Whennosabenxd** [comment]
ok thanks
