### ISSUE TITLE
Bug Report: Character Group Hold Note

### ISSUE THREAD

**Issue by winisrex** [Vortex2Oblivion/LeatherEngine#40]
when u use a character group the characters do the entire animation and the they repeat it if the hold note persists and not the 1st 2 or 3 frames of the animation

it just doesnt looks good

**Comment by AbnormalVDNBfan** [comment]
hola winis, yoo tambien sufro del mismo problema

**Comment by Vortex2Oblivion** [comment]
fixed in [2ae00f9](https://github.com/Vortex2Oblivion/LeatherEngine-Extended-Support/commit/2ae00f9d140052b41609fd651631aae8b249643e)
