### ISSUE TITLE
changing "mod_version" in _polymod_meta.json gets rid of 'mods' in the main menu and disables the mod

### ISSUE THREAD

**Issue by fryman444** [Vortex2Oblivion/LeatherEngine#7]
making "mod_version" anything besides 1.0.0-alpha will cause the mods button in the main menu to disappear and disable the mod you're changing

im not sure if this happens with 2+ mods
![Screenshot 2023-07-21 170101](https://github.com/Vortex2Oblivion/LeatherEngine-Extended-Support/assets/139307130/bcd611d2-6cec-4acc-b59e-f0d7868ee7d1)

**Comment by Vortex2Oblivion** [comment]
it needs to be formatted like 6.0.0
